version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sudin_app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:root@host.docker.internal:5432/sudin_aska
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      WATCHPACK_POLLING: 100
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - sudin_network
    command: npm run dev

networks:
  sudin_network:
    driver: bridge